
package GUI.ThemSuaGUI;


import librarymanagementsystem.BUS.QLPhieuNhapBUS;
import librarymanagementsystem.GUI.*;
import librarymanagementsystem.Toolkit.DataProcessing;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Vector;

public class ThemPhieuNhapForm extends JFrame{
    int x_Mouse, y_Mouse; // For Moving Window
    static String error_mess;
    DataProcessing dp = new DataProcessing();
    static QLPhieuNhapBUS pnBUS = new QLPhieuNhapBUS();
    
    
    
    public ThemPhieuNhapForm() {
        initComponents();
        setSize(830, 592);
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        long millis=System.currentTimeMillis();  
        Date date=new Date(millis);

        jPanel1 = new JPanel();
        addButton = new JLabel();
        exitButton = new JLabel();
        movingWindow = new JLabel();
        maNV_Label = new JTextField();
        maNCC_Label = new JTextField();
        ngayNhap_Label = new JLabel();
        nhanVienForm = new JLabel();
        taoRow_Label = new JLabel();
        tblCTPN = new JTable();
        save_Label=new JLabel();
        jScrollPane1 = new JScrollPane();
        model=new DefaultTableModel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        addButton.setIcon(new ImageIcon(getClass().getResource("../../images/output-onlinepngtools - 2020-05-28T235936.194.png"))); // NOI18N
        addButton.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        addButton.setBounds(10, 7, 35, 35);
        jPanel1.add(addButton);

        exitButton.setIcon(new ImageIcon(getClass().getResource("../../images/output-onlinepngtools (43).png"))); // NOI18N
        exitButton.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        exitButton.setBounds(790, 16, 20, 20);
        jPanel1.add(exitButton);

        movingWindow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                movingWindowMouseDragged(evt);
            }
        });
        movingWindow.addMouseListener(new MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                movingWindowMousePressed(evt);
            }
        });
        movingWindow.setBounds(0, 0, 830, 60);
        jPanel1.add(movingWindow);


        maNV_Label.setBackground(new Color(245, 247, 250));
        maNV_Label.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        maNV_Label.setText("");
        maNV_Label.setBorder(null);
        maNV_Label.setOpaque(false);
        maNV_Label.setBounds(48, 100, 190, 30);
        jPanel1.add(maNV_Label);

        maNCC_Label.setBackground(new Color(245, 247, 250));
        maNCC_Label.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        maNCC_Label.setText("");
        maNCC_Label.setBorder(null);
        maNCC_Label.setOpaque(false);
        maNCC_Label.setBounds(310, 100, 210, 30);
        jPanel1.add(maNCC_Label);

        ngayNhap_Label.setBackground(new Color(245, 247, 250));
        ngayNhap_Label.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        ngayNhap_Label.setText(date.toString());
        ngayNhap_Label.setBorder(null);
        ngayNhap_Label.setOpaque(false);
        ngayNhap_Label.setBounds(557, 100, 160, 30);
        jPanel1.add(ngayNhap_Label);

        save_Label=new JLabel("Save Table");
        save_Label.setBackground(new Color(82, 210, 202));
        save_Label.setFont(new Font("Tahoma", 0, 14));
        save_Label.setOpaque(true);
        save_Label.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        save_Label.setBounds(170, 150, 70, 40);
        jPanel1.add(save_Label);
        save_Label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                for(int i=0;i<tblCTPN.getRowCount();i++){
                    String maPhieuNhap = (String) tblCTPN.getModel().getValueAt(i, 0);
                    String maSach = (String) tblCTPN.getModel().getValueAt(i, 1);
                    System.out.println(maPhieuNhap);
                    System.out.println(maSach);
                    if(check_inputTable(maPhieuNhap, maSach)==true){
                        System.out.println("Lưu Thành Công");
                        new AlertGUI(3, "Success", "Lưu Thành Công!!!", "Quay Lại").setVisible(true);
                    }else{
                        System.err.println(error_mess);
                        System.out.println("Lưu Thất Bại");
                        new AlertGUI(2, "Error", error_mess, "Quay Lại").setVisible(true);
                    }
                }
            }
        });

        taoRow_Label=new JLabel("New Row");
        taoRow_Label.setBackground(new Color(82, 210, 202));
        taoRow_Label.setFont(new Font("Tahoma", 0, 14));
        taoRow_Label.setOpaque(true);
        taoRow_Label.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        taoRow_Label.setBounds(81, 150, 70, 40);
        jPanel1.add(taoRow_Label);
        taoRow_Label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Vector header=new Vector();
                header.add("");
                header.add("");
                header.add("");
                jScrollPane1.getColumnHeader().setVisible(false);
                if(model.getRowCount()==0){
                    model=new DefaultTableModel(header, 0);
                }
                Vector row=new Vector();
                row.add(dp.next_maPhieuNhap(pnBUS.getPKey()));
                row.add("S");
                row.add("0");
                row.add(0);
                model.addRow(row);
                tblCTPN.setModel(model);
            }
        });
        String [] columnName={"MÃ PHIẾU NHẬP", "MÃ SÁCH", "SỐ LƯỢNG"};
        int x=80,y=208;
        headerFields=new JLabel[columnName.length];
        for(int i=0;i<columnName.length;i++){
            headerFields[i] = new JLabel(columnName[i]);
            headerFields[i].setBorder(BorderFactory.createLineBorder(Color.white));
            headerFields[i].setBounds(x, y, 223, 45);
            headerFields[i].setBackground(new Color(82, 210, 202));
            headerFields[i].setFont(new Font("Tahoma", 0, 14));
            headerFields[i].setOpaque(true);
            headerFields[i].setHorizontalAlignment((int) CENTER_ALIGNMENT);
            x=x+223;
            jPanel1.add(headerFields[i]);
        }
        jScrollPane1.setViewportView(tblCTPN);
        jScrollPane1.setBounds(80, 250, 670, 300);
        tblCTPN.setRowHeight(40);

        jPanel1.add(jScrollPane1);

        nhanVienForm.setIcon(new ImageIcon(getClass().getResource("../../images/output-onlinepngtoolsthempn.png"))); // NOI18N
        nhanVienForm.setBounds(0, 0, 830, 592);
        jPanel1.add(nhanVienForm);
        jPanel1.setBounds(0, 0, 830, 592);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean check_inputTable(String maPN, String maSach){
        if (maPN.equals("")){
            error_mess = "Mã Phiếu Nhập trống!!!";
            return false;
        }
        if (maSach.equals("")){
            error_mess = "Mã Sách trống!!!";
            return false;
        }
        if (dp.check_maPhieuNhap(maPN)!=true){
            error_mess = "Mã Phiếu Nhập nhập sai!!!";
            return false;
        }
        if (dp.check_maSach(maSach)!=true){
            error_mess = "Mã Sách nhập sai!!!";
            return false;
        }
        return true;
    }

    private boolean check_input(String maNV,String maNCC, String ngayNhap){
        if (maNV.equals("")){
            error_mess = "Mã Nhân Viên trống!!!";
            return false;
        }
        if (maNCC.equals("")){
            error_mess = "Mã Nhà Cung Cấp trống!!!";
            return false;
        }
        if (ngayNhap.equals("")){
            error_mess = "Ngày Nhập trống!!!";
            return false;
        }
        if (dp.check_maQuanLy(maNV)){
            error_mess = "Mã Nhân Viên nhập sai!!!";
            return false;
        }
        if (dp.check_maNCC(maNCC)){
            error_mess = "Mã Nhà Cung Cấp nhập sai!!!";
            return false;
        }
        if (dp.check_ngaythangnam(ngayNhap)){
            error_mess = "Ngày Nhập nhập sai!!!";
            return false;
        }

        return true;
    }

    private void movingWindowMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movingWindowMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        setLocation(x - x_Mouse, y - y_Mouse);
    }//GEN-LAST:event_movingWindowMouseDragged


    private void movingWindowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movingWindowMousePressed
        x_Mouse = evt.getX();
        y_Mouse = evt.getY();
    }//GEN-LAST:event_movingWindowMousePressed

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitButtonMouseClicked

    private ArrayList<String> getMaSach(){
        ArrayList<String> arrMS =new ArrayList<>();
        for(int i=0;i<tblCTPN.getRowCount();i++){
            String maSach = (String) tblCTPN.getModel().getValueAt(i, 1);
            arrMS.add(maSach);
        }
        return arrMS;
    }
    private ArrayList<Integer> getSoLuong(){
        ArrayList<Integer> arrSL =new ArrayList<>();
        for(int i=0;i<tblCTPN.getRowCount();i++){
            int soLuong = Integer.parseInt((String) tblCTPN.getModel().getValueAt(i, 2));
            arrSL.add(soLuong);
        }
        return arrSL;
    }

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {
        String maNV = maNV_Label.getText();
        String maNCC = maNCC_Label.getText();
        String ngayNhap = ngayNhap_Label.getText();
        String maPhieuNhap = dp.next_maPhieuNhap(pnBUS.getPKey());
        ArrayList<String> maSach = getMaSach();
        ArrayList<Integer> soLuong =getSoLuong();
        System.out.println(maSach);
        System.out.println(soLuong);
        if (check_input(maNV, maNCC, ngayNhap)){
            System.out.println("Nhập Thành Công");
            if (pnBUS.add(maPhieuNhap, ngayNhap, maSach, soLuong, maNV, maNCC, 0, 0)){
                new AlertGUI(3, "Success", "Nhập Phiếu Nhập Thành Công!!!", "Quay Lại").setVisible(true);
                this.dispose();
            }
        }
        else{
            System.err.println(error_mess);
            System.out.println("Nhập Thất Bại");
            new AlertGUI(2, "Error", error_mess, "Quay Lại").setVisible(true);
            // Alert Form
        }

        System.out.println(maNV);
        System.out.println(maNCC);
        System.out.println(ngayNhap);

    }


    public static void main(String[] args) {

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemPhieuNhapForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel addButton;
    private JLabel exitButton;
    private JPanel jPanel1;
    private JLabel nhanVienForm;
    private JLabel movingWindow;
    private JTextField maNV_Label;
    private JTextField maNCC_Label;
    private JLabel ngayNhap_Label;
    private JLabel taoRow_Label;
    private JLabel save_Label;
    private JTable tblCTPN;
    private JLabel [] headerFields;
    private DefaultTableModel model;
    private JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
